### ISSUE TITLE
# being interpreted as comment and excluded

### ISSUE THREAD

**Issue by ghost** [ddksr/cliist#5]
Just a note that the #Proj seems to be interpreted as a comment when adding tasks, so it reads the #, and then excludes everything after it.

This doesn't work:
`
dtl@XPM1:~/cliist/cliist$ ./cliist.py -a #TEST 'testing task 10' @weekend
`
`
Task has no content!
`

However escaping with a \ works:
`
dtl@XPM1:~/cliist/cliist$ ./cliist.py -a \#TEST 'testing task 11' @weekend
`

**Comment by ddksr** [comment]
Thank you for your note. I have # disabled for comments so I never encountered this before.

What would you suggest? This is a similar problem as with exclamation mark (!). I've replaced it with % but I don't think it's the best solution. 

Have you any suggestions?

**Comment by ghost** [comment]
Yeah it's a tough one. I used taskwarrior for years, and how they dealt
with it was like the following:

+weekend (In Todoist this would be considered a label, in taskwarrior a tag)
project:Home (Same in both, this is how you set projects. You could alias
it to pro:home to cut down time as well)
priority:3 (This is the ! mark substitution, in taskwarrior they are L,M,H
instead of numbers)

In taskwarrior:

task add +weekend project:repairs priority:H fix leaky plumbing

**Comment by ddksr** [comment]
I like your idea but I think it would be best to enable this with additional options. Example:
./cliist -a -d today 'something to do' --project MyProject --priority 1
and
./cliist -a -d today 'something to do' -p MyProject -y 1

what do you think? or would you still prefer text parsing?

**Comment by ghost** [comment]
Your idea sounds good (Sorry for the late replies, Gmail has been sorting
these away from my Inbox). I prefer options over the text parsing, feels
more natural to me.

**Comment by ddksr** [comment]
Added --project and --priority

thank you for your input and feedback!
