### ISSUE TITLE
editing task title prompts user to send due date

### ISSUE THREAD

**Issue by shedali** [ddksr/cliist#6]
Hi thanks for the great work! This is an awesome tool. 

I created an inbox task and then edited it.

```
td -e 164450003 'some new text'
```

The CLI responds with 'No due date'

I then add a due date

```
td -e 164450003 'some new text' -d 'today'
```

..and it works

**Comment by ddksr** [comment]
Hello!

thank you for opening this issue, can you please check if it works for you? I removed the validation -- I really don't know why I put it there. =)

And thanks for the great comments, I really appreciate it! 
it's really great to hear if someone likes it =D
