### ISSUE TITLE
Listing tasks due before a certain date

### ISSUE THREAD

**Issue by caodonnell** [ddksr/cliist#9]
I'm trying to use the --lt or --lte option, but I can't figure out how to input in the date I want to use. Every time the output only lists things that are "overdue or today" (as if I didn't use the option).

**Comment by ddksr** [comment]
Hi!

Cliist currently only supports dates in format YYYY-MM-DD. Try this:

```
$ cliist --lte 2015-09-11
```

It will still say Overdue and today because that is the main result set you are filtering from.

Best

**Comment by caodonnell** [comment]
Ah. Thank you - I didn't get the date formatting correct.
